# -*- coding: utf-8 -*-
"""
Informations sur le tableau périodique des éléments.
Ce script vise à génerer des fichiers de données / scripts pour les  qtpe_*

Les données ont été originellement récupérées dans
~/cmd/qtpe  
que j’ai déplacé dans
~/quiz/quiz_tableau_periodique_elements/qtpe_sh/
---
2020-10-13t21:06:35, Création :
    lava@macta
    /Users/lava/quiz/quiz_tableau_periodique_elements/tpe.py
"""

tpe_xx = ['H', 'He', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Ne', 'Na', 'Mg', 'Al', 'Si', 'P', 'S', 'Cl', 'Ar', 'K', 'Ca', 'Sc', 'Ti', 'V', 'Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Ga', 'Ge', 'As', 'Se', 'Br', 'Kr', 'Rb', 'Sr', 'Y', 'Zr', 'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag', 'Cd', 'In', 'Sn', 'Sb', 'Te', 'I', 'Xe', 'Cs', 'Ba', 'La', 'Ce', 'Pr', 'Nd', 'Pm', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', 'Lu', 'Hf', 'Ta', 'W', 'Re', 'Os', 'Ir', 'Pt', 'Au', 'Hg', 'Tl', 'Pb', 'Bi', 'Po', 'At', 'Rn', 'Fr', 'Ra', 'Ac', 'Th', 'Pa', 'U', 'Np', 'Pu', 'Am', 'Cm', 'Bk', 'Cf', 'Es', 'Fm', 'Md', 'No', 'Lr', 'Rf', 'Db', 'Sg', 'Bh', 'Hs', 'Mt', 'Ds', 'Rg', 'Cn', 'Nh', 'Fl', 'Mc', 'Lv', 'Ts', 'Og', ]
tpe_fr = ['Hydrogène', 'Hélium', 'Lithium', 'Béryllium', 'Bore', 'Carbone', 'Azote', 'Oxygène', 'Fluor', 'Néon', 'Sodium', 'Magnésium', 'Aluminium', 'Silicium', 'Phosphore', 'Soufre', 'Chlore', 'Argon', 'Potassium', 'Calcium', 'Scandium', 'Titane', 'Vanadium', 'Chrome', 'Manganèse', 'Fer', 'Cobalt', 'Nickel', 'Cuivre', 'Zinc', 'Gallium', 'Germanium', 'Arsenic', 'Sélénium', 'Brome', 'Krypton', 'Rubidium', 'Strontium', 'Yttrium', 'Zirconium', 'Niobium', 'Molybdène', 'Technétium', 'Ruthénium', 'Rhodium', 'Palladium', 'Argent', 'Cadmium', 'Indium', 'Étain', 'Antimoine', 'Tellure', 'Iode', 'Xénon', 'Césium', 'Baryum', 'Lanthane', 'Cérium', 'Praséodyme', 'Néodyme', 'Prométhium', 'Samarium', 'Europium', 'Gadolinium', 'Terbium', 'Dysprosium', 'Holmium', 'Erbium', 'Thulium', 'Ytterbium', 'Lutécium', 'Hafnium', 'Tantale', 'Tungstène', 'Rhénium', 'Osmium', 'Iridium', 'Platine', 'Or', 'Mercure', 'Thallium', 'Plomb', 'Bismuth', 'Polonium', 'Astate', 'Radon', 'Francium', 'Radium', 'Actinium', 'Thorium', 'Protactinium', 'Uranium', 'Neptunium', 'Plutonium', 'Américium', 'Curium', 'Berkélium', 'Californium', 'Einsteinium', 'Fermium', 'Mendélévium', 'Nobélium', 'Lawrencium', 'Rutherfordium', 'Dubnium', 'Seaborgium', 'Bohrium', 'Hassium', 'Meitnerium', 'Darmstadtium', 'Roentgenium', 'Copernicium', 'Nihonium', 'Flérovium', 'Moscovium', 'Livermorium', 'Tennesse', 'Oganesson', ]
tpe_en = ['Hydrogen', 'Helium', 'Lithium', 'Beryllium', 'Boron', 'Carbon', 'Nitrogen', 'Oxygen', 'Fluorine', 'Neon', 'Sodium', 'Magnesium', 'Aluminium', 'Silicon', 'Phosphorus', 'Sulfur', 'Chlorine', 'Argon', 'Potassium', 'Calcium', 'Scandium', 'Titanium', 'Vanadium', 'Chromium', 'Manganese', 'Iron', 'Cobalt', 'Nickel', 'Copper', 'Zinc', 'Gallium', 'Germanium', 'Arsenic', 'Selenium', 'Bromine', 'Krypton', 'Rubidium', 'Strontium', 'Yttrium', 'Zirconium', 'Niobium', 'Molybdenum', 'Technetium', 'Ruthenium', 'Rhodium', 'Palladium', 'Silver', 'Cadmium', 'Indium', 'Tin', 'Antimony', 'Tellurium', 'Iodine', 'Xenon', 'Cesium', 'Barium', 'Lanthanum', 'Cerium', 'Praseodymium', 'Neodymium', 'Promethium', 'Samarium', 'Europium', 'Gadolinium', 'Terbium', 'Dysprosium', 'Holmium', 'Erbium', 'Thulium', 'Ytterbium', 'Lutetium', 'Hafnium', 'Tantalum', 'Tungten', 'Rhenium', 'Osmium', 'Iridium', 'Platinum', 'Gold', 'Mercury', 'Thallium', 'Lead', 'Bismuth', 'Polonium', 'Astatine', 'Radon', 'Francium', 'Radium', 'Actinium', 'Thorium', 'Protactinium', 'Uranium', 'Neptunium', 'Plutonium', 'Americium', 'Curium', 'Berkelium', 'Californium', 'Einsteinium', 'Fermium', 'Mendelevium', 'Nobelium', 'Lawrencium', 'Rutherfordium', 'Dubnium', 'Seaborgium', 'Bohrium', 'Hassium', 'Meitnerium', 'Darmstadtium', 'Roentgenium', 'Copernicium', 'Nihonium', 'Flerovium', 'Moscovium', 'Livermorium', 'Tennessine', 'Oganesson', ]
tpe_de = ['Wasserstoff', 'Helium', 'Lithium', 'Beryllium', 'Bor', 'Kohlenstoff', 'Stickstoff', 'Sauerstoff', 'Fluor', 'Neon', 'Natrium', 'Magnesium', 'Aluminium', 'Silicium', 'Phosphor', 'Schwefel', 'Chlor', 'Argon', 'Kalium', 'Calcium', 'Scandium', 'Titan', 'Vanadium', 'Chrom', 'Mangan', 'Eisen', 'Cobalt', 'Nickel', 'Kupfer', 'Zink', 'Gallium', 'Germanium', 'Arsen', 'Selen', 'Brom', 'Krypton', 'Rubidium', 'Strontium', 'Yttrium', 'Zirconium', 'Niob', 'Molybdän', 'Technetium', 'Ruthenium', 'Rhodium', 'Palladium', 'Silber', 'Cadmium', 'Indium', 'Zinn', 'Antimon', 'Tellur', 'Iod', 'Xenon', 'Cäsium', 'Barium', 'Lanthan', 'Cer', 'Praseodym', 'Neodym', 'Promethium', 'Samarium', 'Europium', 'Gadolinium', 'Terbium', 'Dysprosium', 'Holmium', 'Erbium', 'Thulium', 'Ytterbium', 'Lutetium', 'Hafnium', 'Tantal', 'Wolfram', 'Rhenium', 'Osmiumu', 'Iridium', 'Platin', 'Gold', 'Quecksilber', 'Thallium', 'Blei', 'Bismut', 'Polonium', 'Astat', 'Radon', 'Francium', 'Radium', 'Actinium', 'Thorium', 'Protaktinium', 'Uran', 'Neptunium', 'Plutonium', 'Americium', 'Curium', 'Berkelium', 'Californium', 'Einsteinium', 'Fermium', 'Mendelevium', 'Nobelium', 'Lawrencium', 'Rutherfordium', 'Dubnium', 'Seaborgium', 'Bohrium', 'Hassium', 'Meitnerium', 'Darmstadtium', 'Röentgenium', 'Copernicium', 'Nihonium', 'Flerovium', 'Moscovium', 'Livermorium', 'Tennessine', 'Oganesson', ]
tpe_it = ['Idrogeno', 'Elio', 'Litio', 'Berillio', 'Boro', 'Carbonio', 'Azoto', 'Ossigeno', 'Fluoro', 'Neon', 'Sodio', 'Magnesio', 'Alluminio', 'Silicio', 'Fosforo', 'Zolfo', 'Cloro', 'Argon', 'Potassio', 'Calcio', 'Scandio', 'Titanio', 'Vanadio', 'Cromo', 'Manganese', 'Ferro', 'Cobalto', 'Nichel', 'Rame', 'Zinco', 'Gallio', 'Germanio', 'Arsenico', 'Selenio', 'Bromo', 'Cripton', 'Rubidio', 'Stronzio', 'Ittrio', 'Zirconio', 'Niobio', 'Molibdeno', 'Tecnezio', 'Rutenio', 'Rodio', 'Palladio', 'Argento', 'Cadmio', 'Indio', 'Stannio', 'Antimonio', 'Tellurio', 'Iodio', 'Xenon', 'Cesio', 'Bario', 'Lantanio', 'Cerio', 'Praseodimio', 'Neodimio', 'Promezio', 'Samario', 'Europio', 'Gadolinio', 'Terbio', 'Disprosio', 'Olmio', 'Erbio', 'Tullio', 'Itterbio', 'Lutezio', 'Afnio', 'Tantalio', 'Tungsteno', 'Renio', 'Osmio', 'Iridio', 'Platino', 'Oro', 'Mercurio', 'Tallio', 'Plombo', 'Bismuto', 'Polonio', 'Astato', 'Radon', 'Francio', 'Radio', 'Attinio', 'Torio', 'Proattinio', 'Uranio', 'Nettunio', 'Plutonio', 'Americio', 'Curio', 'Berkelio', 'Californio', 'Einsteinio', 'Fermio', 'Mendelevio', 'Nobelio', 'Lurenzio', 'Rutherfordio', 'Dubnio', 'Seaborgio', 'Bohrio', 'Hassio', 'Meitnerio', 'Darmstadtio', 'Roentgenio', 'Copernicio', 'Nihonio', 'Flerovio', 'Moscovio', 'Livermorio', 'Tennesso', 'Oganesson', ]

if False:
    with open("./qtpe_c/tpe.dat", 'w') as fw:
        for i, (xx, fr, en, de, it) in \
            enumerate(zip(tpe_xx, tpe_fr, tpe_en, tpe_de, tpe_it)):
            fw.write(f"{i + 1} {xx} {fr} {en} {de} {it}\n")

# Nom le plus long dans chaque langue ?
for lg, tpe in zip(('Fr', 'En', 'De', 'It'),
                   (tpe_fr, tpe_en, tpe_de, tpe_it)):
    longest = max(tpe, key=len)
    maxlen = len(longest)
    print(f"{lg} : len({longest}) = {maxlen}")
